version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mstation-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mstationv2
    ports:
      - "5432:5432"
    volumes:
      - mstation_pgdata:/var/lib/postgresql/data

volumes:
  mstation_pgdata:
